spring:
  application:
    name: api-card-details
server:
  servlet:
    context-path: /card-details


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
      tags:
      application: ${spring.application.name}
    prometheus:
      enabled: true
