apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-card-details
  labels:
    app: api-card-details
  namespace: lights5-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-card-details
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-card-details
    spec:
      containers:
        - name: api-card-details
          image: 922228114461.dkr.ecr.ap-south-1.amazonaws.com/api-card-details
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always


