apiVersion: v1
kind: Deployment
metadata:
  name:
  labels:
    app: api-card-details
spec:
  replicas: 1
  selectors:
    matchLabels:
      app: api-card-details
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-card-details
    spec:
      containers:
        - name: api-card-details
          image: public.ecr.aws/q2n5f9p3/api-card-details:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always


