apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-card-details
  name: api-card-details
  namespace: lights5-api
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: api-card-details
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-card-details
  labels:
    app: api-card-details
  namespace: lights5-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-card-details
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-card-details
    spec:
      containers:
        - name: api-card-details
          image: 514257451212.dkr.ecr.ap-south-1.amazonaws.com/api-card-details
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-card-details
  namespace: lights5-api
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dev-api.nonprod.nb01.local
    http:
      paths:
      - path: /card-details
        pathType: Prefix
        backend:
          service:
            name: api-card-details
            port:
              number: 8080
